version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  onboarding-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onboarding-app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/onboarding?authSource=admin"
    depends_on:
      - mongodb

volumes:
  mongo_data:

networks:
  default:
    name: onboarding-network